# =========================
# Valores del umbrella
# =========================

# --- Backend subchart ---
backend:
  enabled: true
  image:
    repository: ghcr.io/cristianb96/kubernetes_project-backend
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: my-tech.local
        paths:
          - path: /api
            pathType: Prefix
    tls: []

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  env:
    db:
      host: "db"
      port: 5432
      database: "pedido"
      user: "pedido_user"
      password: "pedido_password"

# --- PostgreSQL subchart (Bitnami) ---
db:
  enabled: true
  fullnameOverride: "db"

  auth:
    username: "pedido_user"
    password: "pedido_password"
    database: "pedido"
    postgresPassword: "postgres_admin_pwd"

  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
