image:
  repository: ghcr.io/cristianb96/kubernetes_project-backend
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: my-tech.local
      paths:
        - path: /api
          pathType: Prefix
  tls: []

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 70

resources: {}

env:
  db:
    host: "db-postgresql"
    port: 5432
    database: "pedido"
    user: "pedido_user"
    password: "pedido_password"

# Puedes añadir env extra no sensibles aquí
extraEnv: []
