apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-tech
  namespace: argocd
spec:
  description: "Proyecto ArgoCD para pedido-app"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
