apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.env.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.env.db.password | b64enc | quote }}
