name: Deploy Backend with Helm + ArgoCD

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(date +%Y%m%d%H%M%S)
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE -f Dockerfile backend
          docker push $IMAGE

      - name: Update Helm values with new image
        run: |
          sed -i "s|repository:.*|repository: $(echo $IMAGE | cut -d: -f1)|" charts/pedido-app/values.yaml
          sed -i "s|tag:.*|tag: $(echo $IMAGE | cut -d: -f2)|" charts/pedido-app/values.yaml

      - name: Commit and push Helm chart update
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add charts/pedido-app/values.yaml
          git commit -m "Update backend image to $IMAGE" || echo "No changes to commit"
          git push
